### ISSUE TITLE
Use codemirror for text editing

### ISSUE THREAD

**Issue by tristan-f-r** [Daniel-Tomov/codemonkey#3]
Instead of using a textarea, a codemirror instance for editing the text would be awesome :+1:

**Comment by Daniel-Tomov** [comment]
Yes

**Comment by Daniel-Tomov** [comment]
Fixed with [b863042](https://github.com/Daniel-Tomov/codemonkey/commit/b863042e6028029f3854cf600807d5bc4f82463c)
