### ISSUE TITLE
Redesign home page to follow pro UI/UX techniques

### ISSUE THREAD

**Issue by willuhmjs** [Daniel-Tomov/codemonkey#6]
Examples of this include:
* Unity
* Balance
* Contrast
* Consistency

Possible improvements include:
* Using more appropriate fonts and font sizing.
* Implemening colors accordingly, including proper contrast and unity between nearby text elements.
* Applying the principles of unity to determine how far elements should be from each other, including margins and padding.

**Comment by Daniel-Tomov** [comment]
The UI has recently had changes. Is this issue still relevant?
